# Generated by Django 4.1.1 on 2022-09-08 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
