# Generated by Django 4.1.1 on 2022-09-08 16:22

import ckeditor.fields
from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, max_length=256)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='authors/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
