# Generated by Django 4.1.1 on 2022-09-09 01:12

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_created_at_author_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Primary Point of Interest'),
        ),
    ]
